## Numpy

In [1]:
import platform
print(platform.python_version())

%load_ext watermark
%watermark -a 'Gopala KR' -u -d -v -p watermark,numpy,pandas

3.5.4
Gopala KR 
last updated: 2018-08-30 

CPython 3.5.4
IPython 6.2.1

watermark 1.6.1
numpy 1.15.0
pandas 0.19.2


Most powerful numerical processing library in python. Array Oriented computing.

Provides extension package to python for multi dimensional array.

Very efficient.

Scientific computation.

In [2]:
# Creating a simple array in numpy

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr)

print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
arr = np.arange(10)

print(arr)

print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [4]:
# Proof of efficiency

lst = range(1000)

%timeit [i**2 for i in lst]

523 µs ± 33.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
arr = np.arange(1000)

%timeit arr**2

3.56 µs ± 184 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Creating an Array

In [6]:
arr = np.array([1, 2, 3, 4])

print(arr)

# Print number of dimensions
print(arr.ndim)

# Print shape
print(arr.shape)

# Print length
print(len(arr))

# Print datatype
print(arr.dtype)

# Print item size in byte of each element
print(arr.itemsize)

[1 2 3 4]
1
(4,)
4
int64
8


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

# Print number of dimensions
print(arr.ndim)

# Print shape
print(arr.shape)

# Print length
print(len(arr))

# Print datatype
print(arr.dtype)

# Print item size in byte of each element
print(arr.itemsize)

# Print diagonal elements
print(np.diag(arr))

[[1 2 3]
 [4 5 6]]
2
(2, 3)
2
int64
8
[1 5]


## Functions for creating array

In [8]:
arr = np.ones((3, 3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
arr = np.zeros((3, 3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
arr = np.eye(3, 2)

print(arr)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [12]:
arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
arr = np.arange(1, 10)

print(arr)

[1 2 3 4 5 6 7 8 9]


In [14]:
arr = np.arange(1, 10, 2)

print(arr)

[1 3 5 7 9]


In [15]:
arr = np.random.random((2, 2))

print(arr)

[[0.73194823 0.48089034]
 [0.8926789  0.04258619]]


In [16]:
import numpy as np

print(np.random.random((10,1)))

[[0.55571003]
 [0.14691192]
 [0.99246267]
 [0.16035084]
 [0.86012341]
 [0.7847121 ]
 [0.994885  ]
 [0.8954935 ]
 [0.6125018 ]
 [0.9213751 ]]


## Numpy Indexing

In [17]:
arr = np.arange(10)

print(arr[2])

2


In [18]:
print(arr[10])

IndexError: index 10 is out of bounds for axis 0 with size 10

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[1, 2])

6


In [20]:
arr[1, 2] = 99

print(arr)

[[ 1  2  3]
 [ 4  5 99]]


## Numpy Slicing

In [21]:
arr = np.arange(10)

print(arr)

print(arr[::2])

print(arr[1:4])

print(arr[0:-4])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[1 2 3]
[0 1 2 3 4 5]


In [22]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr)

print(arr[:2, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [23]:
print(arr[1:2, :])

[[5 6 7 8]]


In [24]:
arr = np.array([[1,2],[3,4],[5,6]])

print(arr)

print(arr[[0, 1, 2], [0, 1, 0]])

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


## Numpy Maths

In [25]:
# ELEMENT WISE OPERATIONS

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print(np.add(x, y))

print('*'*40)

print(np.subtract(x, y))

print('*'*40)

print(np.multiply(x, y))

print('*'*40)

print(np.divide(x, y))

[[ 6  8]
 [10 12]]
****************************************
[[-4 -4]
 [-4 -4]]
****************************************
[[ 5 12]
 [21 32]]
****************************************
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [26]:
# Matrix Multiplication

print(np.matmul(x, y))

print('*'*40)

print(np.dot(x,y))

[[19 22]
 [43 50]]
****************************************
[[19 22]
 [43 50]]


In [27]:
x = np.array([[1,2], [3,4]])

print(np.sum(x))

print('*'*40)

print(np.sum(x, axis=0)) # Column Wise

print('*'*40)

print(np.sum(x, axis=1)) # Row wise

10
****************************************
[4 6]
****************************************
[3 7]


In [28]:
print(np.min(x))

print(np.max(x))

1
4


In [29]:
print(x)

print('*'*40)

print(x.T)

[[1 2]
 [3 4]]
****************************************
[[1 3]
 [2 4]]


In [30]:
np.exp(1)

2.718281828459045

In [31]:
np.exp(2)

7.38905609893065

## Statistics

In [32]:
x = np.array([23, 40, 6, 74, 38, 1, 70])
np.mean(x)

36.0

In [33]:
x = np.array([23, 40, 6, 74, 38, 1, 70])
np.median(x)

38.0

In [37]:
from scipy import stats

/home/nbuser/anaconda3_420/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [38]:
x = np.array([23, 40, 6, 38, 38, 1, 70])
stats.mode(x)

ModeResult(mode=array([38]), count=array([2]))

In [39]:
np.std(x)

21.675717628117358

## Assignment

In [40]:
A = np.random.rand(10,1)

print(A)

def func(x):
    return (1 / (1 + np.exp(-x)))

result = np.apply_along_axis(func, 0, A)

print('*'*50)

print(result)

[[0.53198624]
 [0.32745433]
 [0.1418446 ]
 [0.56779528]
 [0.41125703]
 [0.21910519]
 [0.12898398]
 [0.90762615]
 [0.52060521]
 [0.86008194]]
**************************************************
[[0.62994625]
 [0.58113985]
 [0.53540181]
 [0.63825429]
 [0.60138925]
 [0.55455821]
 [0.53220136]
 [0.71251416]
 [0.62728927]
 [0.70267777]]
